// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function fromUnknown(unknown) {
  var func = (
            function (unknown, makeSystemError, makeOtherError) {
                return unknown.syscall === undefined
                    ? makeOtherError(unknown)
                    : makeSystemError(unknown)
            }
        );
  return Curry._3(func, unknown, (function (unknown) {
                return /* SystemError */Block.__(0, [unknown]);
              }), (function (unknown) {
                return /* OtherError */Block.__(1, [unknown]);
              }));
}

exports.fromUnknown = fromUnknown;
/* No side effect */
