// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function fromException(exc) {
  var func = (
            function (makeSystemError, makeOtherError, exc) {
                return exc.syscall === undefined
                    ? makeOtherError(exc)
                    : makeSystemError(exc)
            }
        );
  return Curry._3(func, (function (exc) {
                return /* SystemError */Block.__(0, [exc]);
              }), (function (exc) {
                return /* OtherError */Block.__(1, [exc]);
              }), exc);
}

exports.fromException = fromException;
/* No side effect */
