// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var Relude_IO = require("relude/src/Relude_IO.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var NodeFS__Error = require("./NodeFS__Error.bs.js");
var Relude_Result = require("relude/src/Relude_Result.bs.js");

function _toResult(error, contents) {
  return Curry._2(Relude_Result.mapError, NodeFS__Error.fromException, Relude_Result.flip(Relude_Result.fromOption(contents, error === null ? undefined : Caml_option.some(error))));
}

function readText(encodingOpt, path) {
  var encoding = encodingOpt !== undefined ? encodingOpt : "utf-8";
  return Relude_IO.async((function (resolve) {
                Fs.readFile(path, {
                      encoding: encoding
                    }, (function (error, contents) {
                        return Curry._1(resolve, _toResult(error, contents));
                      }));
                
              }));
}

function readBuffer(path) {
  return Relude_IO.async((function (resolve) {
                Fs.readFile(path, {
                      encoding: null
                    }, (function (error, contents) {
                        return Curry._1(resolve, _toResult(error, contents));
                      }));
                
              }));
}

var $$Error;

exports.$$Error = $$Error;
exports._toResult = _toResult;
exports.readText = readText;
exports.readBuffer = readBuffer;
/* fs Not a pure module */
