// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Relude_IO = require("relude/src/Relude_IO.bs.js");
var NodeFS__Error = require("./NodeFS__Error.bs.js");

function make(path) {
  return Relude_IO.async((function (resolve) {
                var stream = Fs.createReadStream(path);
                stream.on("error", (function (exc) {
                        return Curry._1(resolve, /* Error */Block.__(1, [NodeFS__Error.fromException(exc)]));
                      }));
                stream.on("ready", (function (param) {
                        return Curry._1(resolve, /* Ok */Block.__(0, [stream]));
                      }));
                
              }));
}

exports.make = make;
/* fs Not a pure module */
