// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var $$Error;

var ReadDir;

var ReadFile;

var ReadStream;

var Stat;

var MakeTempDir;

exports.$$Error = $$Error;
exports.ReadDir = ReadDir;
exports.ReadFile = ReadFile;
exports.ReadStream = ReadStream;
exports.Stat = Stat;
exports.MakeTempDir = MakeTempDir;
/* No side effect */
